# Generated by Django 3.1.1 on 2020-12-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mLogin', '0002_auto_20201226_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phonenumber',
            new_name='Phonenumber',
        ),
    ]
