# Generated by Django 3.1.1 on 2020-12-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mLogin', '0004_userphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userphoto',
            old_name='name',
            new_name='uid',
        ),
    ]
