# Generated by Django 3.1.1 on 2020-12-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mLogin', '0005_auto_20201230_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='id',
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
