# Generated by Django 3.1.1 on 2020-12-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mLogin', '0006_auto_20201230_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='uid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
