# Generated by Django 3.1.1 on 2020-12-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mLogin', '0007_auto_20201230_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('user_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='userphoto',
            name='id',
            field=models.AutoField(auto_created=True, default=50, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='uid',
            field=models.BigIntegerField(max_length=50),
        ),
    ]
