# Generated by Django 3.1.1 on 2020-12-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mLogin', '0008_auto_20201230_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
