# Generated by Django 3.1.1 on 2020-12-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mLogin', '0009_delete_userphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('user_Img', models.ImageField(upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
